### ISSUE TITLE
Packaged version

### ISSUE THREAD

**Issue by poochie89** [pziezio/WinUI2XamlIslandSamples#1]
Hey thx for a minimal working example, where you able to make it work with a in a packaged version ?

**Comment by pziezio** [comment]
No sorry, I didn't manage to make packaged version. I've tried that but still got runtime exceptions on launching with some 'unreferenced library somethings...'. You can try it with package versions updated.

I've abandoned the idea of using xaml islands anyway, since MS can't fix Navigation Bar for over a year now. You can see that nested menus doesn't render or render incorrectly when menu bar is collapsed.
